# Generated by Django 5.0.7 on 2024-07-28 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_user_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
